require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'app/models/ability.rb'
  Max: 15

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 11

Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'config/**/*'
    - 'spec/rails_helper.rb'
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/services/find_for_oauth.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 13

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false